# app.py

import os
import helpers.video_to_audio as vt
import helpers.audio_to_text as at
import helpers.extract_text_from_pdf as ep
import helpers.summarize_text as st
import helpers.save_text_to_pdf as sp

import gradio as gr

def generate_summary_from_video(video_file_path: str):
    audio_path = os.path.join("output", "temp_audio.mp3")
    text = at.audio_to_text(vt.video_to_audio(video_file_path, audio_path))
    summary = st.summarize_text(text)
    pdf_path = os.path.join("output", "video_summary.pdf")
    sp.save_text_to_pdf(summary, pdf_path)
    return summary, pdf_path

def generate_summary_from_audio(audio_path: str):
    text = at.audio_to_text(audio_path)
    summary = st.summarize_text(text)
    pdf_path = os.path.join("output", "audio_summary.pdf")
    sp.save_text_to_pdf(summary, pdf_path)
    return summary, pdf_path

def generate_summary_from_pdf(pdf_path: str):
    text = ep.extract_text_from_pdf(pdf_path)
    summary = st.summarize_text(text)
    pdf_path_sum = os.path.join("output", "summarized.pdf")
    sp.save_text_to_pdf(summary, pdf_path_sum)
    return summary, pdf_path_sum

def ask_question_on_summary(question: str, summary: str):
    # Here you can plug in LangChain or a simple LLM
    # For now, just echo back in a “fake QA” style.
    return f"Question: {question}\n\nSimplified answer (demo):\nBased on the summary, this answer is generated by your backend logic."

with gr.Blocks(title="Multimedia Summarizer") as demo:
    gr.Markdown("# 📹 Automated Multimedia Summarization & Translation")
    
    choice = gr.Dropdown(
        choices=[
            "Convert Video to Summarized PDF",
            "Convert Audio to Summarized PDF",
            "Summarize existing PDF"
        ],
        label="Select task"
    )

    video_input = gr.File(label="Upload Video", visible=False)
    audio_input = gr.File(label="Upload Audio", visible=False)
    pdf_input = gr.File(label="Upload PDF", visible=False)

    summary_output = gr.Textbox(label="Summary")
    pdf_output = gr.File(label="Download Summary PDF")

    def switch_visibility(choice_val):
        return {
            video_input: gr.update(visible=choice_val == "Convert Video to Summarized PDF"),
            audio_input: gr.update(visible=choice_val == "Convert Audio to Summarized PDF"),
            pdf_input: gr.update(visible=choice_val == "Summarize existing PDF"),
        }

    choice.change(fn=switch_visibility, inputs=choice, outputs=[video_input, audio_input, pdf_input])

    btn = gr.Button("Generate Summary")

    def run(choice_val, vid=None, aud=None, pdf=None):
        if choice_val == "Convert Video to Summarized PDF":
            return generate_summary_from_video(vid)
        elif choice_val == "Convert Audio to Summarized PDF":
            return generate_summary_from_audio(aud)
        elif choice_val == "Summarize existing PDF":
            return generate_summary_from_pdf(pdf)

    btn.click(
        fn=run,
        inputs=[choice, video_input, audio_input, pdf_input],
        outputs=[summary_output, pdf_output]
    )

    gr.Markdown("## 🤔 Ask a Question about the Summary")
    question_input = gr.Textbox(label="Enter your question")
    answer_output = gr.Textbox(label="Answer")

    question_btn = gr.Button("Ask")

    question_btn.click(
        fn=ask_question_on_summary,
        inputs=[question_input, summary_output],
        outputs=answer_output
    )

demo.launch()
